### ISSUE TITLE
hash passwords with md5

### ISSUE THREAD

**Issue by JJCUBER** [tranpham9/expense-tracker#19]
On the one hand, it might be best to hold off on implementing this until later on since it could make testing endpoints through postman a bit more annoying.  On the other hand, the later we change it, the more annoying it will be to have to either update all accounts to use md5 or wipe the db.

**Comment by JacobGa03** [comment]
This is now down from mobile on both 'login' and 'register'. So before the passwords for either endpoint are sent, they are hashed with MD5.
