### ISSUE TITLE
JWT created on wrong end and with wrong fields

### ISSUE THREAD

**Issue by JJCUBER** [tranpham9/expense-tracker#3]
JWT tokens should be created and signed on the backend (when a user signs in), not frontend.  Additionally, it should have information such as the user's id, name, and email, not password (especially since it is just encoded with base64, i.e. anyone can decode it without too much hassle; we aren't going through the additional process of encrypting it, only signing it).

_I came to these conclusions based on articles about JWT (which I posted in the discord server) and by looking back at the code within the prof's MERN C file._

**Comment by JacobGa03** [comment]
I will make the changes and move it to "backend" so the API can utilize it.

**Comment by JacobGa03** [comment]
Fixed and moved into the proper folder.
