### ISSUE TITLE
Implement JWT for login and register endpoint

### ISSUE THREAD

**Issue by JacobGa03** [tranpham9/expense-tracker#7]
Ensure that upon successful login/register the user is returned a valid JWT.

**Comment by JJCUBER** [comment]
Note that it will only be for login since registration only starts the process; the account isn't fully set up until the email verification process is finished.

**Comment by JacobGa03** [comment]
Not sure if we wan to close this yet. But as far as mobile goes, a JWT is successfully returned. The only fix now, should be removing the nested JSON objects so the JWT is easily accessible ('token' : 'token_here').

**Comment by JJCUBER** [comment]
> Not sure if we wan to close this yet. But as far as mobile goes, a JWT is successfully returned. The only fix now, should be removing the nested JSON objects so the JWT is easily accessible ('token' : 'token_here').

Once the api fixes the layout of the JWT (removing the nesting), we can probably close this.
